name: Sourcemeta One CI

on:
  pull_request:

concurrency:
  group: one-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get update && sudo apt-get install --yes codespell
      - uses: actions/checkout@v4
      - run: codespell docs *.markdown docs/*.md

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build One
        run: make docker PRESET=Release

      - name: Sandbox (headless)
        uses: ./.github/actions/sandbox
        with:
          configuration: headless
          port: 8000

      - name: Sandbox (html)
        uses: ./.github/actions/sandbox
        with:
          configuration: html
          port: 8000

      - name: Sandbox (empty)
        uses: ./.github/actions/sandbox
        with:
          configuration: empty
          port: 8000

      # Public instance
      - run: docker build .  --file public/Dockerfile --progress plain

  website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: mkdocs build --config-file mkdocs.yml --strict --site-dir ./build/website
